---
- name: Configure nginx
  hosts: node
  become: True
  tasks:
    - name: Install nginx
      apt: 
        name: nginx 
        state: present 
        allow_unauthenticated: yes 
#        update_cache: yes

    - name: Copy nginx config file
      template: 
        src: templates/nginx.conf.j2 
        dest: /etc/nginx/sites-available/default 
        mode: '0644'
    
    - name: Restart nginx
      service: 
        name: nginx 
        state: restarted
 
